#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektniZadatakTVP.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProjekatTvp")]
	public partial class NekaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAutori(Autori instance);
    partial void UpdateAutori(Autori instance);
    partial void DeleteAutori(Autori instance);
    partial void InsertKategorije(Kategorije instance);
    partial void UpdateKategorije(Kategorije instance);
    partial void DeleteKategorije(Kategorije instance);
    partial void InsertOcene(Ocene instance);
    partial void UpdateOcene(Ocene instance);
    partial void DeleteOcene(Ocene instance);
    #endregion
		
		public NekaDataContext() : 
				base(global::ProjektniZadatakTVP.Properties.Settings.Default.ProjekatTvpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NekaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NekaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NekaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NekaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Autori> Autoris
		{
			get
			{
				return this.GetTable<Autori>();
			}
		}
		
		public System.Data.Linq.Table<Kategorije> Kategorijes
		{
			get
			{
				return this.GetTable<Kategorije>();
			}
		}
		
		public System.Data.Linq.Table<Ocene> Ocenes
		{
			get
			{
				return this.GetTable<Ocene>();
			}
		}
		
		public System.Data.Linq.Table<Slike> Slikes
		{
			get
			{
				return this.GetTable<Slike>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Autori")]
	public partial class Autori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ime;
		
		private string _prezime;
		
		private System.Nullable<System.DateTime> _datum_rodjenja;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnimeChanging(string value);
    partial void OnimeChanged();
    partial void OnprezimeChanging(string value);
    partial void OnprezimeChanged();
    partial void Ondatum_rodjenjaChanging(System.Nullable<System.DateTime> value);
    partial void Ondatum_rodjenjaChanged();
    #endregion
		
		public Autori()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", DbType="NVarChar(50)")]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this.OnimeChanging(value);
					this.SendPropertyChanging();
					this._ime = value;
					this.SendPropertyChanged("ime");
					this.OnimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezime", DbType="NVarChar(50)")]
		public string prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				if ((this._prezime != value))
				{
					this.OnprezimeChanging(value);
					this.SendPropertyChanging();
					this._prezime = value;
					this.SendPropertyChanged("prezime");
					this.OnprezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum_rodjenja", DbType="Date")]
		public System.Nullable<System.DateTime> datum_rodjenja
		{
			get
			{
				return this._datum_rodjenja;
			}
			set
			{
				if ((this._datum_rodjenja != value))
				{
					this.Ondatum_rodjenjaChanging(value);
					this.SendPropertyChanging();
					this._datum_rodjenja = value;
					this.SendPropertyChanged("datum_rodjenja");
					this.Ondatum_rodjenjaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategorije")]
	public partial class Kategorije : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _naziv_kategorije;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnaziv_kategorijeChanging(string value);
    partial void Onnaziv_kategorijeChanged();
    #endregion
		
		public Kategorije()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naziv_kategorije", DbType="NVarChar(50)")]
		public string naziv_kategorije
		{
			get
			{
				return this._naziv_kategorije;
			}
			set
			{
				if ((this._naziv_kategorije != value))
				{
					this.Onnaziv_kategorijeChanging(value);
					this.SendPropertyChanging();
					this._naziv_kategorije = value;
					this.SendPropertyChanged("naziv_kategorije");
					this.Onnaziv_kategorijeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ocene")]
	public partial class Ocene : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_slike;
		
		private System.Nullable<int> _ocena;
		
		private System.Nullable<System.DateTime> _datum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_slikeChanging(int value);
    partial void Onid_slikeChanged();
    partial void OnocenaChanging(System.Nullable<int> value);
    partial void OnocenaChanged();
    partial void OndatumChanging(System.Nullable<System.DateTime> value);
    partial void OndatumChanged();
    #endregion
		
		public Ocene()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_slike", DbType="Int NOT NULL")]
		public int id_slike
		{
			get
			{
				return this._id_slike;
			}
			set
			{
				if ((this._id_slike != value))
				{
					this.Onid_slikeChanging(value);
					this.SendPropertyChanging();
					this._id_slike = value;
					this.SendPropertyChanged("id_slike");
					this.Onid_slikeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ocena", DbType="Int")]
		public System.Nullable<int> ocena
		{
			get
			{
				return this._ocena;
			}
			set
			{
				if ((this._ocena != value))
				{
					this.OnocenaChanging(value);
					this.SendPropertyChanging();
					this._ocena = value;
					this.SendPropertyChanged("ocena");
					this.OnocenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="Date")]
		public System.Nullable<System.DateTime> datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Slike")]
	public partial class Slike
	{
		
		private int _id;
		
		private System.Nullable<int> _id_autora;
		
		private System.Nullable<int> _id_kategorije;
		
		private string _naziv;
		
		private string _putanjaDoSlike;
		
		public Slike()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_autora", DbType="Int")]
		public System.Nullable<int> id_autora
		{
			get
			{
				return this._id_autora;
			}
			set
			{
				if ((this._id_autora != value))
				{
					this._id_autora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kategorije", DbType="Int")]
		public System.Nullable<int> id_kategorije
		{
			get
			{
				return this._id_kategorije;
			}
			set
			{
				if ((this._id_kategorije != value))
				{
					this._id_kategorije = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naziv", DbType="NVarChar(50)")]
		public string naziv
		{
			get
			{
				return this._naziv;
			}
			set
			{
				if ((this._naziv != value))
				{
					this._naziv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_putanjaDoSlike", DbType="NVarChar(50)")]
		public string putanjaDoSlike
		{
			get
			{
				return this._putanjaDoSlike;
			}
			set
			{
				if ((this._putanjaDoSlike != value))
				{
					this._putanjaDoSlike = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
